BWX SDK: bwx_sdk::bwxLanguage Class Reference
bwx_sdk::bwxLanguage Class Reference
#include <bwx_internat.h>
Public Member Functions
bwxLanguage () noexcept
bwxLanguage (const wxString &sn, const wxString &n, const wxString &un, wxLanguage wxl) noexcept
void SetWxLangCode (wxLanguage l) noexcept
wxLanguage GetWxLangCode () const noexcept
void SetShortName (const wxString &sn) noexcept
const wxString & GetShortName () const noexcept
void SetName (const wxString &n) noexcept
const wxString & GetName () const noexcept
void SetUnicodeName (const wxString &n) noexcept
wxString GetUnicodeName () const noexcept
Detailed Description
Constructor & Destructor Documentation
bwxLanguage() [1/2]
bwx_sdk::bwxLanguage::bwxLanguage () inline noexcept
bwxLanguage() [2/2]
bwx_sdk::bwxLanguage::bwxLanguage (const wxString & sn, const wxString & n, const wxString & un, wxLanguage wxl) inline noexcept
Member Function Documentation
GetName()
const wxString & bwx_sdk::bwxLanguage::GetName () const inline noexcept
GetShortName()
const wxString & bwx_sdk::bwxLanguage::GetShortName () const inline noexcept
Referenced by bwx_sdk::bwxInternat::AddLanguage(), and bwx_sdk::bwxInternat::ResetToDefaultLanguage().
GetUnicodeName()
wxString bwx_sdk::bwxLanguage::GetUnicodeName () const inline noexcept
GetWxLangCode()
wxLanguage bwx_sdk::bwxLanguage::GetWxLangCode () const inline noexcept
Referenced by bwx_sdk::bwxInternat::GetDefaultAppLanguageCode(), and bwx_sdk::bwxInternat::Init().
SetName()
void bwx_sdk::bwxLanguage::SetName (const wxString & n) inline noexcept
SetShortName()
void bwx_sdk::bwxLanguage::SetShortName (const wxString & sn) inline noexcept
SetUnicodeName()
void bwx_sdk::bwxLanguage::SetUnicodeName (const wxString & n) inline noexcept
SetWxLangCode()
void bwx_sdk::bwxLanguage::SetWxLangCode (wxLanguage l) inline noexcept
The documentation for this class was generated from the following file:
E:/C++/Projekty/Libs/bwx_sdk/src/bwx_core/bwx_internat.h