/////////////////////////////////////////////////////////////////////////////
// Name:        bwx_utils.h
// Purpose:     BWXSDK
// Author:      Bartosz Warzocha
// Created:     2018-02-20
// RCS-ID:
// Copyright:   (c) Bartosz Warzocha (bartosz.warzocha@gmail.com)
// Licence:		wxWidgets licence
/////////////////////////////////////////////////////////////////////////////

#ifndef _BWX_UTILS_H_
#define _BWX_UTILS_H_

#include "bwx_sdk/bwx_globals.h"

namespace bwx_sdk {

	/**
	 * @brief Generates a random colour.
	 *
	 * This function generates a random colour. The colour is generated by randomly selecting
	 * red, green and blue components in the range [0, 255].
	 *
	 * @return A random wxColour.
	 *
	 * @example
	 * @code
	 * wxColour colour = bwxGetRandomColour();
	 * // colour will contain a random colour
	 * @endcode
	 */
	wxColour bwxGetRandomColour();
	
	/**
	 * @brief Generates a vector of random colours.
	 *
	 * This function generates a vector of random colours. The number of colours to generate
	 * is specified by the how_many parameter. If the unique parameter is set to true, the
	 * generated colours will be unique. If set to false, the same colour may appear multiple
	 * times in the vector.
	 *
	 * @param v A pointer to a wxVector<wxColour> object to store the generated colours.
	 * @param howMany The number of colours to generate.
	 * @param unique If true, the generated colours will be unique.
	 * @param first The first colour to generate. If unique is set to true, this colour will be included in the vector.
	 *
	 * @example
	 * @code
	 * wxVector<wxColour> colours;
	 * bwxGetRandomColours(&colours, 5, true);
	 * // colours will contain 5 unique random colours
	 * @endcode
	 */
	void bwxGetRandomColours(wxVector<wxColour>* v, int howMany, bool unique = true, const wxColour& first = wxColour(255, 0, 255));

	/**
	 * @brief Mixes two colors based on a given factor.
	 *
	 * This function returns a new color which is the result of mixing the two given colors
	 * using the provided factor. The factor specifies the influence of the second color on
	 * the resulting color. A factor of 0.0 yields the first color, while a factor of 1.0 yields
	 * the second color.
	 *
	 * @param col1 The first color to mix.
	 * @param col2 The second color to mix.
	 * @param factor The mixing factor in the range [0.0, 1.0]. Values outside this range may yield unexpected results.
	 * @return A new wxColour resulting from the mix of col1 and col2.
	 *
	 * @example
	 * @code
	 * wxColour colour1(255, 0, 0);  // Red
	 * wxColour colour2(0, 0, 255);  // Blue
	 * double factor = 0.5;          // Equal mix
	 * wxColour mixedColour = bwxMixColours(colour1, colour2, factor);
	 * // mixedColour will be purple (127, 0, 127)
	 * @endcode
	 */
	wxColour bwxMixColours(const wxColour& col1, const wxColour& col2, double factor);

}

#endif
