BWX SDK: bwx_sdk::bwxProperty< T > Class Template Reference
bwx_sdk::bwxProperty< T > Class Template Reference
Template class representing a property with advanced features.
#include <bwx_oop.h>
Public Types
using Validator = std::function<bool(const T&)>
Validator function to validate new values.
using ChangeCallback = std::function<void(const T&, const T&)>
Callback invoked when the value changes.
using RejectCallback = std::function<void(const T&)>
Callback invoked when a value is rejected.
using Timestamp = std::chrono::system_clock::time_point
Timestamp of the last modification.
Public Member Functions
bwxProperty (const T &defaultValue=T(), Validator validator=nullptr, ChangeCallback onChange=nullptr, RejectCallback onReject=nullptr, size_t historyLimit=0, std::optional< std::chrono::seconds > undoTimeout=std::nullopt, wxEvtHandler *eventHandler=nullptr)
Constructs a Property with optional parameters.
bwxProperty< T > & operator= (const T &newValue)
Assigns a new value to the property.
void set (const T &newValue)
Sets a new value for the property.
const T & get () const noexcept
Retrieves the current value.
const char * AsCStr () const
Converts the value to a C-style string.
void reset ()
Resets the value to its default.
void setValidator (Validator validator)
Sets a new validator function.
void setOnChangeCallback (ChangeCallback onChange)
Assigns a callback for value changes.
void setOnRejectCallback (RejectCallback onReject)
Assigns a callback for value rejections.
void setReadOnly (bool readOnly)
Enables or disables read-only mode.
bool isReadOnly () const noexcept
Checks if the property is read-only.
bool undo ()
Undoes the last value change.
bool redo ()
Redoes the previously undone value change.
void setHistoryLimit (size_t limit)
Sets the history limit for undo/redo operations.
size_t getHistoryLimit () const noexcept
Retrieves the configured history limit.
void clearHistory ()
Clears the undo and redo histories.
void setUndoTimeout (std::chrono::seconds timeout)
Sets the timeout for undo operations.
std::optional< std::chrono::seconds > getUndoTimeout () const noexcept
Retrieves the undo timeout duration.
Timestamp getLastChangeTime () const
Retrieves the timestamp of the last change.
void bind (Property< T > &other)
Binds another property to synchronize value changes.
Property< T > & operator+= (const T &rhs)
Property< T > & operator-= (const T &rhs)
Property< T > & operator*= (const T &rhs)
Property< T > & operator/= (const T &rhs)
bool operator== (const T &rhs) const
bool operator!= (const T &rhs) const
bool operator< (const T &rhs) const
bool operator<= (const T &rhs) const
bool operator> (const T &rhs) const
bool operator>= (const T &rhs) const
Detailed Description
template<typename T>
class bwx_sdk::bwxProperty< T >
Template class representing a property with advanced features.
This class manages a single value with the following capabilities:
Value validation with customizable validator.
Change and rejection callbacks.
Undo/redo functionality with configurable history limit.
Read-only mode to prevent modifications.
wxWidgets event notifications and callback handling.
Timestamp tracking for the last modification.
Property binding to synchronize values between properties.
Arithmetic and comparison operators.
Conversion of the value to C-style strings (for supported types).
Template Parameters
T Type of the value.
Member Typedef Documentation
ChangeCallback
template<typename T > using bwx_sdk::bwxProperty< T >::ChangeCallback = std::function<void(const T&, const T&)>
Callback invoked when the value changes.
RejectCallback
template<typename T > using bwx_sdk::bwxProperty< T >::RejectCallback = std::function<void(const T&)>
Callback invoked when a value is rejected.
Timestamp
template<typename T > using bwx_sdk::bwxProperty< T >::Timestamp = std::chrono::system_clock::time_point
Timestamp of the last modification.
Validator
template<typename T > using bwx_sdk::bwxProperty< T >::Validator = std::function<bool(const T&)>
Validator function to validate new values.
Constructor & Destructor Documentation
bwxProperty()
template<typename T > bwx_sdk::bwxProperty< T >::bwxProperty (const T & defaultValue = T(), Validator validator = nullptr, ChangeCallback onChange = nullptr, RejectCallback onReject = nullptr, size_t historyLimit = 0, std::optional< std::chrono::seconds > undoTimeout = std::nullopt, wxEvtHandler * eventHandler = nullptr) inline explicit
Constructs a Property with optional parameters.
Parameters
defaultValue Initial value of the property.
validator Validator function for new values.
onChange Callback invoked on value change.
onReject Callback invoked when value is rejected.
historyLimit Maximum number of undo/redo states (0 disables history).
undoTimeout Optional timeout for undo operations.
eventHandler Optional wxWidgets event handler for notifications.
Member Function Documentation
AsCStr()
template<typename T > const char * bwx_sdk::bwxProperty< T >::AsCStr () const inline
Converts the value to a C-style string.
Returns
Pointer to the C-string or nullptr if unsupported.
bind()
template<typename T > void bwx_sdk::bwxProperty< T >::bind (Property< T > & other) inline
Binds another property to synchronize value changes.
Parameters
other Property to bind to.
clearHistory()
template<typename T > void bwx_sdk::bwxProperty< T >::clearHistory () inline
Clears the undo and redo histories.
get()
template<typename T > const T & bwx_sdk::bwxProperty< T >::get () const inline nodiscard noexcept
Retrieves the current value.
Returns
Constant reference to the value.
getHistoryLimit()
template<typename T > size_t bwx_sdk::bwxProperty< T >::getHistoryLimit () const inline nodiscard noexcept
Retrieves the configured history limit.
Returns
History limit.
getLastChangeTime()
template<typename T > Timestamp bwx_sdk::bwxProperty< T >::getLastChangeTime () const inline
Retrieves the timestamp of the last change.
Returns
Last change timestamp.
getUndoTimeout()
template<typename T > std::optional< std::chrono::seconds > bwx_sdk::bwxProperty< T >::getUndoTimeout () const inline nodiscard noexcept
Retrieves the undo timeout duration.
Returns
Optional undo timeout.
isReadOnly()
template<typename T > bool bwx_sdk::bwxProperty< T >::isReadOnly () const inline nodiscard noexcept
Checks if the property is read-only.
Returns
True if read-only, false otherwise.
operator!=()
template<typename T > bool bwx_sdk::bwxProperty< T >::operator!= (const T & rhs) const inline
operator*=()
template<typename T > Property< T > & bwx_sdk::bwxProperty< T >::operator*= (const T & rhs) inline
References bwx_sdk::bwxProperty< T >::set().
operator+=()
template<typename T > Property< T > & bwx_sdk::bwxProperty< T >::operator+= (const T & rhs) inline
References bwx_sdk::bwxProperty< T >::set().
operator-=()
template<typename T > Property< T > & bwx_sdk::bwxProperty< T >::operator-= (const T & rhs) inline
References bwx_sdk::bwxProperty< T >::set().
operator/=()
template<typename T > Property< T > & bwx_sdk::bwxProperty< T >::operator/= (const T & rhs) inline
References bwx_sdk::bwxProperty< T >::set().
operator<()
template<typename T > bool bwx_sdk::bwxProperty< T >::operator< (const T & rhs) const inline
operator<=()
template<typename T > bool bwx_sdk::bwxProperty< T >::operator<= (const T & rhs) const inline
operator=()
template<typename T > bwxProperty< T > & bwx_sdk::bwxProperty< T >::operator= (const T & newValue) inline
Assigns a new value to the property.
Parameters
newValue Value to assign.
Returns
Reference to the updated property.
References bwx_sdk::bwxProperty< T >::set().
operator==()
template<typename T > bool bwx_sdk::bwxProperty< T >::operator== (const T & rhs) const inline
operator>()
template<typename T > bool bwx_sdk::bwxProperty< T >::operator> (const T & rhs) const inline
operator>=()
template<typename T > bool bwx_sdk::bwxProperty< T >::operator>= (const T & rhs) const inline
redo()
template<typename T > bool bwx_sdk::bwxProperty< T >::redo () inline
Redoes the previously undone value change.
Returns
True if successful, false otherwise.
reset()
template<typename T > void bwx_sdk::bwxProperty< T >::reset () inline
Resets the value to its default.
References bwx_sdk::bwxProperty< T >::set().
set()
template<typename T > void bwx_sdk::bwxProperty< T >::set (const T & newValue) inline
Sets a new value for the property.
Parameters
newValue Value to set.
Referenced by bwx_sdk::bwxProperty< T >::operator*=(), bwx_sdk::bwxProperty< T >::operator+=(), bwx_sdk::bwxProperty< T >::operator-=(), bwx_sdk::bwxProperty< T >::operator/=(), bwx_sdk::bwxProperty< T >::operator=(), and bwx_sdk::bwxProperty< T >::reset().
setHistoryLimit()
template<typename T > void bwx_sdk::bwxProperty< T >::setHistoryLimit (size_t limit) inline
Sets the history limit for undo/redo operations.
Parameters
limit Number of history entries to retain.
setOnChangeCallback()
template<typename T > void bwx_sdk::bwxProperty< T >::setOnChangeCallback (ChangeCallback onChange) inline
Assigns a callback for value changes.
Parameters
onChange Callback to set.
setOnRejectCallback()
template<typename T > void bwx_sdk::bwxProperty< T >::setOnRejectCallback (RejectCallback onReject) inline
Assigns a callback for value rejections.
Parameters
onReject Callback to set.
setReadOnly()
template<typename T > void bwx_sdk::bwxProperty< T >::setReadOnly (bool readOnly) inline
Enables or disables read-only mode.
Parameters
readOnly True to enable, false to disable.
setUndoTimeout()
template<typename T > void bwx_sdk::bwxProperty< T >::setUndoTimeout (std::chrono::seconds timeout) inline
Sets the timeout for undo operations.
Parameters
timeout Timeout duration.
setValidator()
template<typename T > void bwx_sdk::bwxProperty< T >::setValidator (Validator validator) inline
Sets a new validator function.
Parameters
validator Validator function to set.
undo()
template<typename T > bool bwx_sdk::bwxProperty< T >::undo () inline
Undoes the last value change.
Returns
True if successful, false otherwise.
The documentation for this class was generated from the following file:
E:/C++/Projekty/Libs/bwx_sdk/src/bwx_core/bwx_oop.h