.TH "E:/C++/Projekty/Libs/bwx_sdk/src/bwx_core/bwx_string.h" 3 "Version 1.0.0" "BWX SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/C++/Projekty/Libs/bwx_sdk/src/bwx_core/bwx_string.h
.SH SYNOPSIS
.br
.PP
\fR#include 'bwx_sdk/bwx_globals\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBbwx_sdk\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "wxArrayString \fBbwx_sdk::bwxSimpleExplode\fP (const wxString &str, const wxString &separator)"
.br
.ti -1c
.RI "void \fBbwx_sdk::bwxSimpleExplode\fP (wxArrayString *a, const wxString &str, const wxString &separator)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BWX SDK from the source code\&.
