.TH "E:/C++/Projekty/Libs/bwx_sdk/src/bwx_core/bwx_internat.h" 3 "Version 1.0.0" "BWX SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/C++/Projekty/Libs/bwx_sdk/src/bwx_core/bwx_internat.h
.SH SYNOPSIS
.br
.PP
\fR#include <wx/intl\&.h>\fP
.br
\fR#include <wx/filename\&.h>\fP
.br
\fR#include <wx/log\&.h>\fP
.br
\fR#include <algorithm>\fP
.br
\fR#include <vector>\fP
.br
\fR#include 'bwx_sdk/bwx_globals\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBbwx_sdk::bwxLanguage\fP"
.br
.ti -1c
.RI "class \fBbwx_sdk::bwxInternat\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBbwx_sdk\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBbwx_sdk::WX_DECLARE_STRING_HASH_MAP\fP (\fBbwxLanguage\fP, LangMap)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "constexpr auto \fBbwx_sdk::bwxDEFAULT_LANG_FOLDER\fP = 'locale'"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BWX SDK from the source code\&.
