.TH "E:/C++/Projekty/Libs/bwx_sdk/src/bwx_core/bwx_internat.cpp" 3 "Version 1.0.0" "BWX SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/C++/Projekty/Libs/bwx_sdk/src/bwx_core/bwx_internat.cpp \- Implements the bwxInternat class for internationalization\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <wx/wxprec\&.h>\fP
.br
\fR#include <wx/wx\&.h>\fP
.br
\fR#include 'bwx_internat\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBbwx_sdk\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Implements the bwxInternat class for internationalization\&. 

The bwxInternat class extends wxLocale to provide convenient methods for setting up languages, loading catalogs, and managing default application language\&. 
.PP
Definition in file \fBbwx_internat\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for BWX SDK from the source code\&.
