.TH "E:/C++/Projekty/Libs/bwx_sdk/src/bwx_core/bwx_cmd.h" 3 "Version 1.0.0" "BWX SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/C++/Projekty/Libs/bwx_sdk/src/bwx_core/bwx_cmd.h
.SH SYNOPSIS
.br
.PP
\fR#include <wx/cmdline\&.h>\fP
.br
\fR#include 'bwx_sdk/bwx_globals\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBbwx_sdk::bwxCmdLineParser\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBbwx_sdk\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BWX SDK from the source code\&.
