.TH "E:/C++/Projekty/Libs/bwx_sdk/src/bwx_utils/bwx_utils.cpp" 3 "Version 1.0.0" "BWX SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/C++/Projekty/Libs/bwx_sdk/src/bwx_utils/bwx_utils.cpp \- Implements utility functions for the BWXSDK library\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <wx/wxprec\&.h>\fP
.br
\fR#include <wx/wx\&.h>\fP
.br
\fR#include 'bwx_sdk/bwx_core/bwx_math\&.h'\fP
.br
\fR#include 'bwx_utils\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBbwx_sdk\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "wxColour \fBbwx_sdk::bwxMixColours\fP (const wxColour &col1, const wxColour &col2, double factor)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Implements utility functions for the BWXSDK library\&. 


.PP
Definition in file \fBbwx_utils\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for BWX SDK from the source code\&.
