.TH "E:/C++/Projekty/Libs/bwx_sdk/src/bwx_core/bwx_string.cpp" 3 "Version 1.0.0" "BWX SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/C++/Projekty/Libs/bwx_sdk/src/bwx_core/bwx_string.cpp \- Implements basic string functions used within the BWX_SDK Library\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <wx/wxprec\&.h>\fP
.br
\fR#include <wx/wx\&.h>\fP
.br
\fR#include 'bwx_string\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBbwx_sdk\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "wxArrayString \fBbwx_sdk::bwxSimpleExplode\fP (const wxString &str, const wxString &separator)"
.br
.ti -1c
.RI "void \fBbwx_sdk::bwxSimpleExplode\fP (wxArrayString *a, const wxString &str, const wxString &separator)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Implements basic string functions used within the BWX_SDK Library\&. 


.PP
Definition in file \fBbwx_string\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for BWX SDK from the source code\&.
