.TH "E:/C++/Projekty/Libs/bwx_sdk/src/bwx_core/bwx_core.cpp" 3 "Version 1.0.0" "BWX SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/C++/Projekty/Libs/bwx_sdk/src/bwx_core/bwx_core.cpp \- Implements core functions for the BWXSDK\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <wx/wxprec\&.h>\fP
.br
\fR#include <wx/wx\&.h>\fP
.br
\fR#include <wx/stdpaths\&.h>\fP
.br
\fR#include 'bwx_core\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBbwx_sdk\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBbwx_sdk::bwxStdPathsInfo\fP (void)"
.br
.RI "Displays standard system paths in a message box\&. "
.ti -1c
.RI "void \fBbwx_sdk::bwxAddByteFlag\fP (int &var, bwxByteFlag flag) noexcept"
.br
.RI "Adds a bit flag to a variable\&. "
.ti -1c
.RI "void \fBbwx_sdk::bwxRemoveByteFlag\fP (int &var, bwxByteFlag flag) noexcept"
.br
.RI "Removes a bit flag from a variable\&. "
.ti -1c
.RI "bool \fBbwx_sdk::bwxIsByteFlagSet\fP (const int &var, bwxByteFlag flag) noexcept"
.br
.RI "Checks whether a bit flag is set in a variable\&. "
.ti -1c
.RI "void \fBbwx_sdk::bwxSetByteFlag\fP (int &var, bwxByteFlag flag) noexcept"
.br
.RI "Overwrites a variable with a specific bit flag\&. "
.ti -1c
.RI "wxString \fBbwx_sdk::bwxGetThreadErrorDescription\fP (const wxThreadError &err, bool processLog)"
.br
.RI "Retrieves a description for a thread error\&. "
.ti -1c
.RI "wxString \fBbwx_sdk::bwxGetSemaphoreErrorDescription\fP (const wxSemaError &err, bool processLog)"
.br
.RI "Retrieves a description for a semaphore error\&. "
.ti -1c
.RI "wxString \fBbwx_sdk::bwxGetMutexErrorDescritpion\fP (const wxMutexError &err, bool processLog)"
.br
.RI "Retrieves a description for a mutex error\&. "
.in -1c
.SH "Detailed Description"
.PP 
Implements core functions for the BWXSDK\&. 

This file provides basic functions such as displaying standard system paths, performing bit flag operations, and retrieving error descriptions for various multithreading-related errors\&. 
.PP
Definition in file \fBbwx_core\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for BWX SDK from the source code\&.
