.TH "bwx_sdk::bwxLanguage" 3 "Version 1.0.0" "BWX SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bwx_sdk::bwxLanguage
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <bwx_internat\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBbwxLanguage\fP () noexcept"
.br
.ti -1c
.RI "\fBbwxLanguage\fP (const wxString &sn, const wxString &n, const wxString &un, wxLanguage wxl) noexcept"
.br
.ti -1c
.RI "void \fBSetWxLangCode\fP (wxLanguage l) noexcept"
.br
.ti -1c
.RI "wxLanguage \fBGetWxLangCode\fP () const noexcept"
.br
.ti -1c
.RI "void \fBSetShortName\fP (const wxString &sn) noexcept"
.br
.ti -1c
.RI "const wxString & \fBGetShortName\fP () const noexcept"
.br
.ti -1c
.RI "void \fBSetName\fP (const wxString &n) noexcept"
.br
.ti -1c
.RI "const wxString & \fBGetName\fP () const noexcept"
.br
.ti -1c
.RI "void \fBSetUnicodeName\fP (const wxString &n) noexcept"
.br
.ti -1c
.RI "wxString \fBGetUnicodeName\fP () const noexcept"
.br
.in -1c
.SH "Detailed Description"
.PP 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "bwx_sdk::bwxLanguage::bwxLanguage ()\fR [inline]\fP, \fR [noexcept]\fP"

.SS "bwx_sdk::bwxLanguage::bwxLanguage (const wxString & sn, const wxString & n, const wxString & un, wxLanguage wxl)\fR [inline]\fP, \fR [noexcept]\fP"

.SH "Member Function Documentation"
.PP 
.SS "const wxString & bwx_sdk::bwxLanguage::GetName () const\fR [inline]\fP, \fR [noexcept]\fP"

.SS "const wxString & bwx_sdk::bwxLanguage::GetShortName () const\fR [inline]\fP, \fR [noexcept]\fP"

.PP
Referenced by \fBbwx_sdk::bwxInternat::AddLanguage()\fP, and \fBbwx_sdk::bwxInternat::ResetToDefaultLanguage()\fP\&.
.SS "wxString bwx_sdk::bwxLanguage::GetUnicodeName () const\fR [inline]\fP, \fR [noexcept]\fP"

.SS "wxLanguage bwx_sdk::bwxLanguage::GetWxLangCode () const\fR [inline]\fP, \fR [noexcept]\fP"

.PP
Referenced by \fBbwx_sdk::bwxInternat::GetDefaultAppLanguageCode()\fP, and \fBbwx_sdk::bwxInternat::Init()\fP\&.
.SS "void bwx_sdk::bwxLanguage::SetName (const wxString & n)\fR [inline]\fP, \fR [noexcept]\fP"

.SS "void bwx_sdk::bwxLanguage::SetShortName (const wxString & sn)\fR [inline]\fP, \fR [noexcept]\fP"

.SS "void bwx_sdk::bwxLanguage::SetUnicodeName (const wxString & n)\fR [inline]\fP, \fR [noexcept]\fP"

.SS "void bwx_sdk::bwxLanguage::SetWxLangCode (wxLanguage l)\fR [inline]\fP, \fR [noexcept]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for BWX SDK from the source code\&.
