.TH "E:/C++/Projekty/Libs/bwx_sdk/src/bwx_core/bwx_cmd.cpp" 3 "Version 1.0.0" "BWX SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/C++/Projekty/Libs/bwx_sdk/src/bwx_core/bwx_cmd.cpp \- Implements easy to use command line parser derivating from wxCmdLineParser\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <wx/wxprec\&.h>\fP
.br
\fR#include <wx/wx\&.h>\fP
.br
\fR#include 'bwx_cmd\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBbwx_sdk\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Implements easy to use command line parser derivating from wxCmdLineParser\&. 


.PP
Definition in file \fBbwx_cmd\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for BWX SDK from the source code\&.
