.TH "E:/C++/Projekty/Libs/bwx_sdk/src/bwx_utils/bwx_utils.h" 3 "Version 1.0.0" "BWX SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/C++/Projekty/Libs/bwx_sdk/src/bwx_utils/bwx_utils.h
.SH SYNOPSIS
.br
.PP
\fR#include 'bwx_sdk/bwx_globals\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBbwx_sdk\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "wxColour \fBbwx_sdk::bwxMixColours\fP (const wxColour &col1, const wxColour &col2, double factor)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BWX SDK from the source code\&.
