.TH "bwx_sdk::bwxInternat" 3 "Version 1.0.0" "BWX SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bwx_sdk::bwxInternat
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <bwx_internat\&.h>\fP
.PP
Inherits wxLocale\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBbwxInternat\fP ()"
.br
.RI "Default constructor\&. "
.ti -1c
.RI "\fBbwxInternat\fP (const \fBbwxLanguage\fP &l)"
.br
.RI "Constructs a \fBbwxInternat\fP object with a specified language\&. "
.ti -1c
.RI "\fBbwxInternat\fP (const wxString &short_name, const wxString &name, const wxString &uname, wxLanguage wx_lang_code)"
.br
.RI "Constructs a \fBbwxInternat\fP object with language parameters\&. "
.ti -1c
.RI "bool \fBInit\fP (const wxString &short_name=wxEmptyString)"
.br
.RI "Initializes the locale using a language short name\&. "
.ti -1c
.RI "bool \fBInitByName\fP (const wxString &name)"
.br
.RI "Initializes the locale by the full language name\&. "
.ti -1c
.RI "void \fBSetDefaultAppLanguage\fP (const \fBbwxLanguage\fP &l) noexcept"
.br
.ti -1c
.RI "void \fBSetDefaultAppLanguage\fP (const wxString &short_name, const wxString &name, const wxString &uname, wxLanguage wx_lang_code) noexcept"
.br
.RI "Sets the default application language\&. "
.ti -1c
.RI "\fBbwxLanguage\fP \fBGetDefaultAppLanguage\fP () const noexcept"
.br
.ti -1c
.RI "wxLanguage \fBGetDefaultAppLanguageCode\fP () const noexcept"
.br
.ti -1c
.RI "void \fBAddLanguage\fP (const \fBbwxLanguage\fP &l)"
.br
.RI "Adds a language to the internal language map\&. "
.ti -1c
.RI "void \fBAddLanguage\fP (const wxString &short_name, const wxString &name, const wxString &uname, wxLanguage wx_lang_code)"
.br
.RI "Adds a language to the internal language map using parameters\&. "
.ti -1c
.RI "void \fBAddLanguageSystemDefault\fP ()"
.br
.RI "Adds the system default language\&. "
.ti -1c
.RI "void \fBAddLanguageEnglish\fP ()"
.br
.RI "Adds English to the language map\&. "
.ti -1c
.RI "void \fBAddLanguagePolish\fP ()"
.br
.RI "Adds Polish to the language map\&. "
.ti -1c
.RI "void \fBAddLanguageGerman\fP ()"
.br
.RI "Adds German to the language map\&. "
.ti -1c
.RI "wxArrayString \fBGetLangNames\fP () const"
.br
.RI "Retrieves the list of full language names\&. "
.ti -1c
.RI "void \fBSetLangFolderName\fP (const wxString &name) noexcept"
.br
.ti -1c
.RI "const wxString & \fBGetLangFolderName\fP () const noexcept"
.br
.ti -1c
.RI "void \fBUseShortCatalogNames\fP () noexcept"
.br
.ti -1c
.RI "void \fBDontUseShortCatalogNames\fP () noexcept"
.br
.ti -1c
.RI "void \fBResetToDefaultLanguage\fP ()"
.br
.RI "Resets the locale to the default language\&. "
.in -1c
.SH "Detailed Description"
.PP 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "bwx_sdk::bwxInternat::bwxInternat ()"

.PP
Default constructor\&. Constructs a \fBbwxInternat\fP object using the default system language and enables the use of short catalog names\&. 
.PP
References \fBAddLanguageSystemDefault()\fP, and \fBUseShortCatalogNames()\fP\&.
.SS "bwx_sdk::bwxInternat::bwxInternat (const \fBbwxLanguage\fP & l)\fR [explicit]\fP"

.PP
Constructs a \fBbwxInternat\fP object with a specified language\&. Adds the system default language, then adds the provided language, sets it as the default, and enables the use of short catalog names\&.
.PP
\fBParameters\fP
.RS 4
\fIl\fP A \fBbwxLanguage\fP object representing the language to add\&. 
.RE
.PP

.PP
References \fBAddLanguage()\fP, \fBAddLanguageSystemDefault()\fP, \fBSetDefaultAppLanguage()\fP, and \fBUseShortCatalogNames()\fP\&.
.SS "bwx_sdk::bwxInternat::bwxInternat (const wxString & short_name, const wxString & name, const wxString & uname, wxLanguage wx_lang_code)"

.PP
Constructs a \fBbwxInternat\fP object with language parameters\&. Adds the system default language, then adds the language defined by the provided parameters, sets it as the default, and enables the use of short catalog names\&.
.PP
\fBParameters\fP
.RS 4
\fIshort_name\fP Short identifier for the language\&. 
.br
\fIname\fP Full name of the language\&. 
.br
\fIuname\fP Unique name for the language\&. 
.br
\fIwx_lang_code\fP wxWidgets language code\&. 
.RE
.PP

.PP
References \fBAddLanguage()\fP, \fBAddLanguageSystemDefault()\fP, \fBSetDefaultAppLanguage()\fP, and \fBUseShortCatalogNames()\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void bwx_sdk::bwxInternat::AddLanguage (const \fBbwxLanguage\fP & l)"

.PP
Adds a language to the internal language map\&. 
.PP
\fBParameters\fP
.RS 4
\fIl\fP A \fBbwxLanguage\fP object to add\&. 
.RE
.PP

.PP
References \fBbwx_sdk::bwxLanguage::GetShortName()\fP\&.
.PP
Referenced by \fBAddLanguageEnglish()\fP, \fBAddLanguageGerman()\fP, \fBAddLanguagePolish()\fP, \fBAddLanguageSystemDefault()\fP, \fBbwxInternat()\fP, and \fBbwxInternat()\fP\&.
.SS "void bwx_sdk::bwxInternat::AddLanguage (const wxString & short_name, const wxString & name, const wxString & uname, wxLanguage wx_lang_code)"

.PP
Adds a language to the internal language map using parameters\&. 
.PP
\fBParameters\fP
.RS 4
\fIshort_name\fP Short identifier for the language\&. 
.br
\fIname\fP Full name of the language\&. 
.br
\fIuname\fP Unique name for the language\&. 
.br
\fIwx_lang_code\fP wxWidgets language code\&. 
.RE
.PP

.SS "void bwx_sdk::bwxInternat::AddLanguageEnglish ()"

.PP
Adds English to the language map\&. 
.PP
References \fBAddLanguage()\fP\&.
.SS "void bwx_sdk::bwxInternat::AddLanguageGerman ()"

.PP
Adds German to the language map\&. 
.PP
References \fBAddLanguage()\fP\&.
.SS "void bwx_sdk::bwxInternat::AddLanguagePolish ()"

.PP
Adds Polish to the language map\&. 
.PP
References \fBAddLanguage()\fP\&.
.SS "void bwx_sdk::bwxInternat::AddLanguageSystemDefault ()"

.PP
Adds the system default language\&. This method adds a language entry representing the system default\&. 
.PP
References \fBAddLanguage()\fP\&.
.PP
Referenced by \fBbwxInternat()\fP, \fBbwxInternat()\fP, and \fBbwxInternat()\fP\&.
.SS "void bwx_sdk::bwxInternat::DontUseShortCatalogNames ()\fR [inline]\fP, \fR [noexcept]\fP"

.SS "\fBbwxLanguage\fP bwx_sdk::bwxInternat::GetDefaultAppLanguage () const\fR [inline]\fP, \fR [noexcept]\fP"

.SS "wxLanguage bwx_sdk::bwxInternat::GetDefaultAppLanguageCode () const\fR [inline]\fP, \fR [noexcept]\fP"

.PP
References \fBbwx_sdk::bwxLanguage::GetWxLangCode()\fP\&.
.SS "const wxString & bwx_sdk::bwxInternat::GetLangFolderName () const\fR [inline]\fP, \fR [noexcept]\fP"

.SS "wxArrayString bwx_sdk::bwxInternat::GetLangNames () const"

.PP
Retrieves the list of full language names\&. Iterates over the internal language map and returns an array of language names\&.
.PP
\fBReturns\fP
.RS 4
A wxArrayString containing the names of all languages in the map\&. 
.RE
.PP

.SS "bool bwx_sdk::bwxInternat::Init (const wxString & short_name = \fRwxEmptyString\fP)"

.PP
Initializes the locale using a language short name\&. If the provided short name is empty, the system language is used\&. If the system language is unknown, the default language is used instead\&. Once the language code is determined, the locale is initialized and the language catalogs are loaded\&.
.PP
\fBParameters\fP
.RS 4
\fIshort_name\fP The short name of the language to initialize\&. 
.RE
.PP
\fBReturns\fP
.RS 4
True if initialization and catalog loading succeeded; false otherwise\&. 
.RE
.PP

.PP
References \fBbwx_sdk::bwxLanguage::GetWxLangCode()\fP\&.
.PP
Referenced by \fBInitByName()\fP, and \fBResetToDefaultLanguage()\fP\&.
.SS "bool bwx_sdk::bwxInternat::InitByName (const wxString & name)"

.PP
Initializes the locale by the full language name\&. Searches the internal language map for a language whose full name matches the provided name\&. If found, the locale is initialized using the corresponding short name\&.
.PP
\fBParameters\fP
.RS 4
\fIname\fP The full name of the language\&. 
.RE
.PP
\fBReturns\fP
.RS 4
True if initialization succeeded; false otherwise\&. 
.RE
.PP

.PP
References \fBInit()\fP\&.
.SS "void bwx_sdk::bwxInternat::ResetToDefaultLanguage ()"

.PP
Resets the locale to the default language\&. Re-initializes the locale using the default language's short name\&. 
.PP
References \fBbwx_sdk::bwxLanguage::GetShortName()\fP, and \fBInit()\fP\&.
.SS "void bwx_sdk::bwxInternat::SetDefaultAppLanguage (const \fBbwxLanguage\fP & l)\fR [inline]\fP, \fR [noexcept]\fP"

.PP
Referenced by \fBbwxInternat()\fP, and \fBbwxInternat()\fP\&.
.SS "void bwx_sdk::bwxInternat::SetDefaultAppLanguage (const wxString & short_name, const wxString & name, const wxString & uname, wxLanguage wx_lang_code)\fR [noexcept]\fP"

.PP
Sets the default application language\&. Updates the default language used by the application\&.
.PP
\fBParameters\fP
.RS 4
\fIshort_name\fP Short identifier for the language\&. 
.br
\fIname\fP Full name of the language\&. 
.br
\fIuname\fP Unique name for the language\&. 
.br
\fIwx_lang_code\fP wxWidgets language code\&. 
.RE
.PP

.SS "void bwx_sdk::bwxInternat::SetLangFolderName (const wxString & name)\fR [inline]\fP, \fR [noexcept]\fP"

.SS "void bwx_sdk::bwxInternat::UseShortCatalogNames ()\fR [inline]\fP, \fR [noexcept]\fP"

.PP
Referenced by \fBbwxInternat()\fP, \fBbwxInternat()\fP, and \fBbwxInternat()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BWX SDK from the source code\&.
