.TH "E:/C++/Projekty/Libs/bwx_sdk/src/bwx_core Directory Reference" 3 "Version 1.0.0" "BWX SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/C++/Projekty/Libs/bwx_sdk/src/bwx_core Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBbwx_cmd\&.cpp\fP"
.br
.RI "Implements easy to use command line parser derivating from wxCmdLineParser\&. "
.ti -1c
.RI "file \fBbwx_cmd\&.h\fP"
.br
.ti -1c
.RI "file \fBbwx_core\&.cpp\fP"
.br
.RI "Implements core functions for the BWXSDK\&. "
.ti -1c
.RI "file \fBbwx_core\&.h\fP"
.br
.ti -1c
.RI "file \fBbwx_internat\&.cpp\fP"
.br
.RI "Implements the bwxInternat class for internationalization\&. "
.ti -1c
.RI "file \fBbwx_internat\&.h\fP"
.br
.ti -1c
.RI "file \fBbwx_math\&.cpp\fP"
.br
.RI "Implements basic mathematical functions used within the BWX_SDK Library\&. "
.ti -1c
.RI "file \fBbwx_math\&.h\fP"
.br
.ti -1c
.RI "file \fBbwx_oop\&.h\fP"
.br
.ti -1c
.RI "file \fBbwx_string\&.cpp\fP"
.br
.RI "Implements basic string functions used within the BWX_SDK Library\&. "
.ti -1c
.RI "file \fBbwx_string\&.h\fP"
.br
.in -1c
