BWX SDK: bwx_sdk::bwxInternat Class Reference
bwx_sdk::bwxInternat Class Reference
#include <bwx_internat.h>
Public Member Functions
bwxInternat ()
Default constructor.
bwxInternat (const bwxLanguage &l)
Constructs a bwxInternat object with a specified language.
bwxInternat (const wxString &short_name, const wxString &name, const wxString &uname, wxLanguage wx_lang_code)
Constructs a bwxInternat object with language parameters.
bool Init (const wxString &short_name=wxEmptyString)
Initializes the locale using a language short name.
bool InitByName (const wxString &name)
Initializes the locale by the full language name.
void SetDefaultAppLanguage (const bwxLanguage &l) noexcept
void SetDefaultAppLanguage (const wxString &short_name, const wxString &name, const wxString &uname, wxLanguage wx_lang_code) noexcept
Sets the default application language.
bwxLanguage GetDefaultAppLanguage () const noexcept
wxLanguage GetDefaultAppLanguageCode () const noexcept
void AddLanguage (const bwxLanguage &l)
Adds a language to the internal language map.
void AddLanguage (const wxString &short_name, const wxString &name, const wxString &uname, wxLanguage wx_lang_code)
Adds a language to the internal language map using parameters.
void AddLanguageSystemDefault ()
Adds the system default language.
void AddLanguageEnglish ()
Adds English to the language map.
void AddLanguagePolish ()
Adds Polish to the language map.
void AddLanguageGerman ()
Adds German to the language map.
wxArrayString GetLangNames () const
Retrieves the list of full language names.
void SetLangFolderName (const wxString &name) noexcept
const wxString & GetLangFolderName () const noexcept
void UseShortCatalogNames () noexcept
void DontUseShortCatalogNames () noexcept
void ResetToDefaultLanguage ()
Resets the locale to the default language.
Detailed Description
Constructor & Destructor Documentation
bwxInternat() [1/3]
bwx_sdk::bwxInternat::bwxInternat ()
Default constructor.
Constructs a bwxInternat object using the default system language and enables the use of short catalog names.
References AddLanguageSystemDefault(), and UseShortCatalogNames().
bwxInternat() [2/3]
bwx_sdk::bwxInternat::bwxInternat (const bwxLanguage & l) explicit
Constructs a bwxInternat object with a specified language.
Adds the system default language, then adds the provided language, sets it as the default, and enables the use of short catalog names.
Parameters
l A bwxLanguage object representing the language to add.
References AddLanguage(), AddLanguageSystemDefault(), SetDefaultAppLanguage(), and UseShortCatalogNames().
bwxInternat() [3/3]
bwx_sdk::bwxInternat::bwxInternat (const wxString & short_name, const wxString & name, const wxString & uname, wxLanguage wx_lang_code)
Constructs a bwxInternat object with language parameters.
Adds the system default language, then adds the language defined by the provided parameters, sets it as the default, and enables the use of short catalog names.
Parameters
short_name Short identifier for the language.
name Full name of the language.
uname Unique name for the language.
wx_lang_code wxWidgets language code.
References AddLanguage(), AddLanguageSystemDefault(), SetDefaultAppLanguage(), and UseShortCatalogNames().
Member Function Documentation
AddLanguage() [1/2]
void bwx_sdk::bwxInternat::AddLanguage (const bwxLanguage & l)
Adds a language to the internal language map.
Parameters
l A bwxLanguage object to add.
References bwx_sdk::bwxLanguage::GetShortName().
Referenced by AddLanguageEnglish(), AddLanguageGerman(), AddLanguagePolish(), AddLanguageSystemDefault(), bwxInternat(), and bwxInternat().
AddLanguage() [2/2]
void bwx_sdk::bwxInternat::AddLanguage (const wxString & short_name, const wxString & name, const wxString & uname, wxLanguage wx_lang_code)
Adds a language to the internal language map using parameters.
Parameters
short_name Short identifier for the language.
name Full name of the language.
uname Unique name for the language.
wx_lang_code wxWidgets language code.
AddLanguageEnglish()
void bwx_sdk::bwxInternat::AddLanguageEnglish ()
Adds English to the language map.
References AddLanguage().
AddLanguageGerman()
void bwx_sdk::bwxInternat::AddLanguageGerman ()
Adds German to the language map.
References AddLanguage().
AddLanguagePolish()
void bwx_sdk::bwxInternat::AddLanguagePolish ()
Adds Polish to the language map.
References AddLanguage().
AddLanguageSystemDefault()
void bwx_sdk::bwxInternat::AddLanguageSystemDefault ()
Adds the system default language.
This method adds a language entry representing the system default.
References AddLanguage().
Referenced by bwxInternat(), bwxInternat(), and bwxInternat().
DontUseShortCatalogNames()
void bwx_sdk::bwxInternat::DontUseShortCatalogNames () inline noexcept
GetDefaultAppLanguage()
bwxLanguage bwx_sdk::bwxInternat::GetDefaultAppLanguage () const inline noexcept
GetDefaultAppLanguageCode()
wxLanguage bwx_sdk::bwxInternat::GetDefaultAppLanguageCode () const inline noexcept
References bwx_sdk::bwxLanguage::GetWxLangCode().
GetLangFolderName()
const wxString & bwx_sdk::bwxInternat::GetLangFolderName () const inline noexcept
GetLangNames()
wxArrayString bwx_sdk::bwxInternat::GetLangNames () const
Retrieves the list of full language names.
Iterates over the internal language map and returns an array of language names.
Returns
A wxArrayString containing the names of all languages in the map.
Init()
bool bwx_sdk::bwxInternat::Init (const wxString & short_name = wxEmptyString)
Initializes the locale using a language short name.
If the provided short name is empty, the system language is used. If the system language is unknown, the default language is used instead. Once the language code is determined, the locale is initialized and the language catalogs are loaded.
Parameters
short_name The short name of the language to initialize.
Returns
True if initialization and catalog loading succeeded; false otherwise.
References bwx_sdk::bwxLanguage::GetWxLangCode().
Referenced by InitByName(), and ResetToDefaultLanguage().
InitByName()
bool bwx_sdk::bwxInternat::InitByName (const wxString & name)
Initializes the locale by the full language name.
Searches the internal language map for a language whose full name matches the provided name. If found, the locale is initialized using the corresponding short name.
Parameters
name The full name of the language.
Returns
True if initialization succeeded; false otherwise.
References Init().
ResetToDefaultLanguage()
void bwx_sdk::bwxInternat::ResetToDefaultLanguage ()
Resets the locale to the default language.
Re-initializes the locale using the default language's short name.
References bwx_sdk::bwxLanguage::GetShortName(), and Init().
SetDefaultAppLanguage() [1/2]
void bwx_sdk::bwxInternat::SetDefaultAppLanguage (const bwxLanguage & l) inline noexcept
Referenced by bwxInternat(), and bwxInternat().
SetDefaultAppLanguage() [2/2]
void bwx_sdk::bwxInternat::SetDefaultAppLanguage (const wxString & short_name, const wxString & name, const wxString & uname, wxLanguage wx_lang_code) noexcept
Sets the default application language.
Updates the default language used by the application.
Parameters
short_name Short identifier for the language.
name Full name of the language.
uname Unique name for the language.
wx_lang_code wxWidgets language code.
SetLangFolderName()
void bwx_sdk::bwxInternat::SetLangFolderName (const wxString & name) inline noexcept
UseShortCatalogNames()
void bwx_sdk::bwxInternat::UseShortCatalogNames () inline noexcept
Referenced by bwxInternat(), bwxInternat(), and bwxInternat().
The documentation for this class was generated from the following files:
E:/C++/Projekty/Libs/bwx_sdk/src/bwx_core/bwx_internat.h
E:/C++/Projekty/Libs/bwx_sdk/src/bwx_core/bwx_internat.cpp