name: LINUX

on:
  push:
    branches:
      - master
    paths:
      - 'include/**'
      - 'src/**'
      - 'examples/**'
  pull_request:
    branches:
      - master
    paths:
      - 'include/**'
      - 'src/**'
      - 'examples/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Release, Debug]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.22.0'

      - name: Install required packages (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            autoconf \
            automake \
            libtool \
            pkg-config \
            ninja-build \
            build-essential \
            libglib2.0-dev \
            libfontconfig1-dev \
            libfreetype6-dev \
            libpng-dev \
            libxrender-dev \
            libxcb1-dev \
            libxcb-render0-dev \
            libxcb-shm0-dev 
          pip3 install --upgrade meson
        shell: bash

      - name: Install required packages (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew update
          brew install ninja pkg-config gettext
          brew link --force gettext
        shell: bash

      - name: Cache vcpkg and dependencies
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/vcpkg
            ${{ github.workspace }}/build/vcpkg_installed
            ${{ github.workspace }}/vcpkg/downloads
          key: ${{ runner.os }}-vcpkg-${{ hashFiles('vcpkg.json') }}

      - name: Prepare vcpkg
        run: |
          if [ ! -d "vcpkg" ]; then
            git clone https://github.com/microsoft/vcpkg.git
          fi
          cd vcpkg
          git pull origin master
          ./bootstrap-vcpkg.sh || ./bootstrap-vcpkg.bat
        shell: bash

      - name: Set VCPKG Triplet
        id: set_triplet
        run: |
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            echo "VCPKG_TRIPLET=x64-windows" >> "$GITHUB_ENV"
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            echo "VCPKG_TRIPLET=x64-osx" >> "$GITHUB_ENV"
          else
            echo "VCPKG_TRIPLET=x64-linux" >> "$GITHUB_ENV"
          fi
        shell: bash

      - name: Install dependencies via vcpkg
        run: |
          ./vcpkg/vcpkg install --triplet $VCPKG_TRIPLET
        shell: bash

      - name: Configure CMake (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          BUILD_DIR="build/${{ matrix.os }}-${{ matrix.build_type }}"
          mkdir -p "$BUILD_DIR"
          cmake -B "$BUILD_DIR" -S . \
            -G "Visual Studio 17 2022" \
            -A x64 \
            -DCMAKE_TOOLCHAIN_FILE="${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake" \
            -DVCPKG_TARGET_TRIPLET="$VCPKG_TRIPLET" \
            -DCMAKE_BUILD_TYPE="${{ matrix.build_type }}" \
            -DBUILD_SHARED_LIBS=OFF
        shell: bash

      - name: Configure CMake (Linux & macOS)
        if: matrix.os != 'windows-latest'
        run: |
          BUILD_DIR="build/${{ matrix.os }}-${{ matrix.build_type }}"
          mkdir -p "$BUILD_DIR"
          cmake -B "$BUILD_DIR" -S . \
            -G Ninja \
            -DCMAKE_TOOLCHAIN_FILE="${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake" \
            -DVCPKG_TARGET_TRIPLET="$VCPKG_TRIPLET" \
            -DCMAKE_BUILD_TYPE="${{ matrix.build_type }}" \
            -DBUILD_SHARED_LIBS=OFF
        shell: bash

      - name: Build
        run: |
          BUILD_DIR="build/${{ matrix.os }}-${{ matrix.build_type }}"
          cmake --build "$BUILD_DIR" --config "${{ matrix.build_type }}"
        shell: bash

      - name: Run tests (if any)
        run: |
          BUILD_DIR="build/${{ matrix.os }}-${{ matrix.build_type }}"
          cd "$BUILD_DIR"
          ctest --output-on-failure --build-config "${{ matrix.build_type }}"
        shell: bash
