name: LINUX

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  LINUX:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        build_type: [Debug, Release]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        export CFLAGS="-D_strnicmp=strncasecmp -I/usr/include/audio -I/opt/vc/include $CFLAGS"
        export CXXFLAGS="-D_strnicmp=strncasecmp -I/usr/include/audio -I/opt/vc/include $CXXFLAGS"
        
        sudo apt-get update
        sudo apt-get install -y \
            build-essential \
            cmake \
            ninja-build \
            g++ \
            autoconf \
            automake \
            libtool \
            pkg-config \
            libtool-bin \
            m4 \
            nasm \
            gettext \
            bison \
            flex \
            gfortran \
            python3-pip \
            meson \
            libfontconfig1-dev \
            libfreetype6-dev \
            libglib2.0-dev \
            libgtk-3-dev \
            libx11-dev \
            libxext-dev \
            libxrender-dev \
            libpng-dev \
            zlib1g-dev \
            libdbus-1-dev \
            libatk1.0-dev \
            libxi-dev \
            libxtst-dev \
            gobject-introspection \
            python3-gi \
            libcairo2-dev \
            libpango1.0-dev \
            libgdk-pixbuf2.0-dev \
            libxinerama-dev \
            libxrandr-dev \
            libxcomposite-dev \
            libxdamage-dev \
            libxcursor-dev \
            libxfixes-dev \
            libxss-dev \
            libepoxy-dev \
            libwayland-dev \
            libinput-dev \
            libasound2-dev \
            libpulse-dev \
            libxft-dev \
            libxkbcommon-dev \
            libegl1-mesa-dev \
            libibus-1.0-dev \
            mesa-common-dev \
            libgl1-mesa-dev \
            libxxf86vm-dev \
            libaudio-dev \
            libraspberrypi-dev

    - name: Set up vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg
        git pull
        ./bootstrap-vcpkg.sh
      env:
        VCPKG_ROOT: ${{ github.workspace }}/vcpkg

    - name: Install vcpkg dependencies
      run: |
        ./vcpkg/vcpkg install --triplet x64-linux
      env:
        VCPKG_ROOT: ${{ github.workspace }}/vcpkg

    - name: Configure CMake
      run: |
        VCPKG_TRIPLET=x64-linux
        BUILD_DIR="build/linux-${{ matrix.build_type }}"
        mkdir -p "$BUILD_DIR"
        cmake -B "$BUILD_DIR" -S . \
          -G Ninja \
          -DCMAKE_TOOLCHAIN_FILE="${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake" \
          -DVCPKG_TARGET_TRIPLET="$VCPKG_TRIPLET" \
          -DCMAKE_BUILD_TYPE="${{ matrix.build_type }}" \
          -DBUILD_SHARED_LIBS=OFF \
          -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
      env:
        VCPKG_ROOT: ${{ github.workspace }}/vcpkg

    - name: Build project
      run: |
        BUILD_DIR="build/linux-${{ matrix.build_type }}"
        cmake --build "$BUILD_DIR"

    - name: Run tests
      run: |
        BUILD_DIR="build/linux-${{ matrix.build_type }}"
        cd "$BUILD_DIR"
        ctest -V

    - name: Upload build logs on failure
      if: failure()
      uses: actions/upload-artifact@v4.6.0
      with:
        name: build-logs
        path: |
          ${{ github.workspace }}/vcpkg/buildtrees/libxcrypt/autoconf-x64-linux-out.log
          ${{ github.workspace }}/vcpkg/buildtrees/libxcrypt/autoconf-x64-linux-err.log