name: LINUX

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install required Python packages
      run: |
        python -m pip install --upgrade pip
        pip install colorama

    - name: Set up vcpkg
      uses: microsoft/vcpkg-action@v2
      with:
        vcpkgDirectory: ${{ runner.temp }}/vcpkg
        vcpkgGitURL: 'https://github.com/microsoft/vcpkg'
        vcpkgCommitId: 'master'
        cleanAfterBuild: true

    - name: Configure and build with CMake
      run: |
        mkdir -p build
        cd build
        cmake -DCMAKE_TOOLCHAIN_FILE=${{ runner.temp }}/vcpkg/scripts/buildsystems/vcpkg.cmake ..
        cmake --build .

    - name: Run tests
      run: |
        cd build
        ctest -V