name: LINUX

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install required Python packages
      run: |
        python -m pip install --upgrade pip
        pip install colorama

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y ninja-build cmake g++ libgtk-3-dev

    - name: Set up vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        ./vcpkg/bootstrap-vcpkg.sh
      env:
        VCPKG_ROOT: ${{ github.workspace }}/vcpkg

    - name: Validate vcpkg manifest
      run: python init_lib_project.py

    - name: Configure CMake
      run: |
        mkdir -p build
        cd build
        cmake -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake ..
      env:
        VCPKG_ROOT: ${{ github.workspace }}/vcpkg

    - name: Build project
      run: |
        cd build
        cmake --build .

    - name: Run tests
      run: |
        cd build
        ctest -V