name: C++ CI/CD

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false  # Zapobiega przerywaniu wszystkich zadań po pierwszym błędzie
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Release, Debug]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.22.0'

      - name: Cache vcpkg and dependencies
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/vcpkg
            ${{ github.workspace }}/build/vcpkg_installed
            ${{ github.workspace }}/vcpkg/downloads
          key: ${{ runner.os }}-vcpkg-${{ hashFiles('vcpkg.json') }}

      - name: Install vcpkg
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            ./bootstrap-vcpkg.bat
          else
            ./bootstrap-vcpkg.sh
          fi
        shell: bash

      - name: Install dependencies
        run: |
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            VCPKG_TRIPLET="x64-windows"
            vcpkg_command=".\\vcpkg\\vcpkg.exe"
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            VCPKG_TRIPLET="x64-osx"
            vcpkg_command="./vcpkg/vcpkg"
          else
            VCPKG_TRIPLET="x64-linux"
            vcpkg_command="./vcpkg/vcpkg"
          fi

          echo "Installing dependencies for triplet: $VCPKG_TRIPLET"
          $vcpkg_command install --triplet $VCPKG_TRIPLET --clean-after-build
        shell: bash

      - name: Configure CMake
        run: |
          BUILD_DIR="build/${{ matrix.os }}-${{ matrix.build_type }}"
          mkdir -p "$BUILD_DIR"

          cmake -B "$BUILD_DIR" -S . \
            -DCMAKE_TOOLCHAIN_FILE="${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake" \
            -DVCPKG_TARGET_TRIPLET="$VCPKG_TRIPLET" \
            -DCMAKE_BUILD_TYPE="${{ matrix.build_type }}" \
            -DCMAKE_PREFIX_PATH="${{ github.workspace }}/vcpkg_installed/$VCPKG_TRIPLET" \
            -DBUILD_SHARED_LIBS=OFF 
        shell: bash

      - name: Build
        run: |
          BUILD_DIR="build/${{ matrix.os }}-${{ matrix.build_type }}"
          cmake --build "$BUILD_DIR" --config "${{ matrix.build_type }}"
        shell: bash

      - name: Run tests (if any)
        run: |
          BUILD_DIR="build/${{ matrix.os }}-${{ matrix.build_type }}"
          cd "$BUILD_DIR"
          ctest --output-on-failure --build-config "${{ matrix.build_type }}"
        shell: bash
