name: C++ CI/CD

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Release, Debug]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.22.0'

      - name: Install required Linux packages (for Linux builds)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            autoconf \
            automake \
            libtool \
            pkg-config \
            ninja-build \
            build-essential \
            libssl-dev \
            libffi-dev \
            libgmp-dev \
            libpcre3-dev \
            gettext \
            texinfo \
            m4
        shell: bash

      - name: Install required macOS packages (for macOS builds)
        if: matrix.os == 'macos-latest'
        run: |
          brew update
          brew install cmake ninja pkg-config gettext
          brew link --force gettext
        shell: bash

      - name: Install required Windows packages (for Windows builds)
        if: matrix.os == 'windows-latest'
        run: |
          choco install ninja -y
        shell: powershell

      - name: Cache vcpkg and dependencies
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/vcpkg
            ${{ github.workspace }}/build/vcpkg_installed
            ${{ github.workspace }}/vcpkg/downloads
          key: ${{ runner.os }}-vcpkg-${{ hashFiles('vcpkg.json') }}

      - name: Prepare vcpkg directory
        run: |
          if [ ! -d "vcpkg" ]; then
            git clone https://github.com/microsoft/vcpkg.git
          else
            echo "vcpkg directory already exists. Skipping clone."
          fi
        shell: bash

      - name: Bootstrap vcpkg
        run: |
          cd vcpkg
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            ./bootstrap-vcpkg.bat
          else
            ./bootstrap-vcpkg.sh
          fi
        shell: bash

      - name: Set VCPKG Triplet
        id: set_triplet
        run: |
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            echo "VCPKG_TRIPLET=x64-windows" >> "$GITHUB_ENV"
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            echo "VCPKG_TRIPLET=x64-osx" >> "$GITHUB_ENV"
          else
            echo "VCPKG_TRIPLET=x64-linux" >> "$GITHUB_ENV"
          fi
        shell: bash

      - name: Install dependencies
        run: |
          echo "Installing dependencies for triplet: $VCPKG_TRIPLET"
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            .\\vcpkg\\vcpkg.exe install --triplet $VCPKG_TRIPLET --clean-after-build
          else
            ./vcpkg/vcpkg install --triplet $VCPKG_TRIPLET --clean-after-build --x-manifest-root="${{ github.workspace }}"
          fi
        shell: bash

      - name: Configure CMake
        run: |
          BUILD_DIR="build/${{ matrix.os }}-${{ matrix.build_type }}"
          mkdir -p "$BUILD_DIR"

          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            CMAKE_GENERATOR="-G \"Visual Studio 17 2022\" -A x64"
          elif [[ "${{ matrix.os }}" == "macos-latest" || "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            CMAKE_GENERATOR="-G Ninja"
          fi

          cmake -B "$BUILD_DIR" -S . \
            -DCMAKE_TOOLCHAIN_FILE="${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake" \
            -DVCPKG_TARGET_TRIPLET="$VCPKG_TRIPLET" \
            -DCMAKE_BUILD_TYPE="${{ matrix.build_type }}" \
            -DCMAKE_PREFIX_PATH="${{ github.workspace }}/vcpkg_installed/$VCPKG_TRIPLET" \
            -DBUILD_SHARED_LIBS=OFF \
            $CMAKE_GENERATOR
        shell: bash

      - name: Build
        run: |
          BUILD_DIR="build/${{ matrix.os }}-${{ matrix.build_type }}"
          cmake --build "$BUILD_DIR" --config "${{ matrix.build_type }}"
        shell: bash

      - name: Run tests (if any)
        run: |
          BUILD_DIR="build/${{ matrix.os }}-${{ matrix.build_type }}"
          cd "$BUILD_DIR"
          ctest --output-on-failure --build-config "${{ matrix.build_type }}"
        shell: bash
